kind: Namespace
apiVersion: v1
metadata:
  name: qa
  labels:
    name: qa
    app: my-python-app
---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
  labels:
    name: prod
    app: my-python-app
